language: php

php:
    - 7.4

before_script:
    - pecl install pcov
    - phpenv config-rm xdebug.ini
    - composer global require hirak/prestissimo -o --no-ansi --no-suggest
    - composer install -o --no-ansi --no-suggest

script:
    - vendor/bin/phpcs bin src tests --ignore=Data --standard=ruleset.xml
    - vendor/bin/phpstan analyse bin src tests -c ruleset.neon -l 8 --error-format custom
    - vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml
    - chmod +x bin/phpunit-coverage-analyzer && bin/phpunit-coverage-analyzer
    - export INFECTION=INFECTION && vendor/bin/infection -j8 --coverage=var/coverage --only-covered --no-ansi && export INFECTION

after_success:
    - vendor/bin/php-coveralls

notifications:
    email: false
