name: Workflow

on:
    push:
        branches:
            - master
    schedule:
        -   cron: '0 0 * * *'

jobs:
    job:
        name: Job
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v3
            -   uses: shivammathur/setup-php@v2
            -   name: Step
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    composer install --ignore-platform-reqs --no-ansi
                    vendor/bin/phpcs bin src tests --standard=ruleset.xml
                    vendor/bin/phpcs bin src tests -vvv --standard=ruleset.xml | bin/phpcs-analyzer
                    vendor/bin/phpstan analyse bin src tests -c ruleset.neon -l 8
                    vendor/bin/phpunit && cat /tmp/log.xml | bin/phpunit-analyzer
                    vendor/bin/phpunit cat /tmp/log.xml | bin/phpunit-coverage-analyzer 99
                    export INFECTION=INFECTION && vendor/bin/infection -j8 --only-covered --no-ansi && export INFECTION
                    vendor/bin/php-coveralls
            -   uses: Mattraks/delete-workflow-runs@v2
                with:
                    token: ${{ github.token }}
                    repository: ${{ github.repository }}
                    retain_days: 1
                    keep_minimum_runs: 7
